import type { Metadata } from "next";
// import { Plus_Jakarta_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const plusJakarta = localFont({
  src: [
    {
      path: "../public/fonts/plus-jakarta/PlusJakartaSans-VariableFont_wght.woff2",
      weight: "200 800",
      style: "normal",
    },
    {
      path: "../public/fonts/plus-jakarta/PlusJakartaSans-Italic-VariableFont_wght.woff2",
      weight: "200 800",
      style: "italic",
    },
  ],
  variable: "--font-plus-jakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakarta.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
